repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.0.1
  hooks:
    - id: check-added-large-files

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.0.1
  hooks:
    - id: debug-statements
      args: ['--pattern', 'print\(|pdb|import pdb|from icecream import ic']
      name: debug-statements
      entry: bash -c 'grep -rnE "$1" "$2" || exit 0' --
      language: system
      files: '^.*\.(py|js|java|cpp|h)$'
