[tool.poetry]
name = "autolog"
version = "0.1.0"
description = ""
authors = ["Brandon Leon <brandonleon@pm.me>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
click = "^8.1.7"
typer = "^0.9.0"
icecream = "^2.1.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
